# Generated by Django 4.2.11 on 2024-05-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='pw',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='un',
            field=models.CharField(default='b', max_length=50),
            preserve_default=False,
        ),
    ]
